- hosts: image-converter
  sudo: yes
  remote_user: ec2-user
  tasks:
#
    - name: update yum
      yum: name=* state=latest
#
    - name: install & start Docker
      yum: name=docker state=latest
#
    - name: start Docker service
      service: name=docker state=started
#
    - name: install python
      yum: name=python state=latest
#
    - name: install docker-py
      pip: name=docker-py version=1.1.0
#
    - name: run go-thumber
      docker: 
        name: go-thumber
        image: ikait/go-thumber
        state: started
        ports: "80:8081"
